install:
  - git submodule update --init
  - set PATH=%PATH%;C:\cygwin\bin
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt

build_script:
  - make

test_script:
  - make -j check
