dist: trusty
sudo: false

language: c

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

matrix:
  allow_failures:
    - os: linux
      compiler: clang

addons:
  apt:
    packages:
      - gcc-multilib

script:
  - make
